language: c
sudo: required

dist: xenial

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    update: true
    packages:
      - pkg-config csh cmake
      - gfortran
      - openmpi-bin libopenmpi-dev libopenmpi1.10
      - netcdf-bin libnetcdf-dev libnetcdff-dev libnetcdf11

git:
  depth: 3
  quiet: true

env:
  matrix:
  - TYPE=ubuntu
  global:
  - FC=gfortran
  - OMPI_FC=${FC}

matrix:
  allow_failures:
  - env: TYPE=ACCESS-OM
  - env: TYPE=ACCESS-CM

script:
  - make $TYPE

before_deploy:
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"
  - tar -czvf binary_release.tar.gz Linux/*

deploy:
  provider: releases
  api_key:
    secure: jLzUE9fuKptzwSZyNbHXunqy4ltk2P6rXI2a3qIZqKEpHjmXI9fYMEXwSxtDDQAa/RK3aDUaxDJpuZodK4D+D4s2aKsX6IccPNezRl1c4TYxF4QNCfLLykCw/O7Ilb1XcNsXFH4Q6MAkbRVX/3X7myDsNijyFc+SYNFQYz4qL1w=
  file: binary_release.tar.gz
  skip_cleanup: true
  on:
    repo: OceansAus/oasis3-mct
    branch: master
